#pragma config(Sensor, S1,     ss,             sensorSONAR)
#pragma config(Sensor, S2,     ts,             sensorTouch)
#pragma config(Sensor, S3,     ls,             sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int ssv, tsv, lsv;			//set variables
	setSensorType(S1, ss);
	setSensorType(S2, ts);
	setSensorType(S3, ls);

	while(1) {
		ssv = SensorValue(ss);		//set variables
		tsv = SensorValue(ts);
		lsv = SensorValue(ls);

		nMotorEncoder[motorB] = 0;		//initialization
		nMotorEncoder[motorC] = 0;
		bFloatDuringInactiveMotorPWM = false;
		wait1Msec(7000);  //pause for 7 seconds

		while(lsv >= 40) {			// There is high level light, 40 is Threshold value
			while(1){
				while(tsv != 1) {			// There isn't any touch
					while((ssv >= 5) || (ssv <= 10)) {		// distance to wall is 5cm< ssv <10cm
						motor[motorB] = 50;
						motor[motorC] = 50;
					}
					while(ssv > 10) {								// distance to right wall over 10cm then turn right
						motor[motorB] = 0;
						motor[motorC] = 20;
					}
					while (ssv < 5) {
						motor[motorB] = 20;					// when distance to right wall under 5cm then turn left
						motor[motorC] = 0;
					}
				}
				if(tsv == 1) {			//  There is touch
					bFloatDuringInactiveMotorPWM = false;
					wait1Msec(1000);
					motor[motorB] = -40;
					motor[motorC] = -40;
					bFloatDuringInactiveMotorPWM = false;
					wait1Msec(1000);
					motor[motorB] = -50;
					motor[motorC] = 50;
				}
			}
		}
		while(lsv < 40) {   // There is low level light
			motor[motorB] = 0;
			motor[motorC] = 0;
			bFloatDuringInactiveMotorPWM = false;
		}
	}
}
