#pragma config(Sensor, S1,     sonar,          sensorSONAR)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int ssv, tsv, lsv;			//set variables

	while(lsv > 0) 
	{
			ssv = SensorValue[sonar];		//set variables
			tsv = SensorValue[touch];
			lsv = SensorValue[light];
			nxtDisplayTextLine(2, "%d cm", ssv);
			nxtDisplayTextLine(3, "%d light", lsv);

			if((ssv >= 10) && (ssv <= 20))  	// when distance to right wall is 10cm <= ssv <= 20cm
			{	
					motor[motorB] = 40;
					motor[motorC] = 40;
					wait1Msec(100);
			}
			if((ssv > 20)&&(ssv <=255)) // when distance to right wall over 20cm then turn right
			{							
					motor[motorB] = 15;
					motor[motorC] = 25;
					wait1Msec(50);
			}
			if((ssv <10)&&(ssv >= 0)) // when distance to right wall under 10cm then turn left
			{								
					motor[motorB] = 25;
					motor[motorC] = 15;
					wait1Msec(50);
			}
			if(tsv == 1) //  if there is touch
			{		
					bFloatDuringInactiveMotorPWM = false;
					wait1Msec(500);
					motor[motorB] = -30;
					motor[motorC] = -30;
					wait1Msec(200);
					nMotorEncoder[motorB] = 0;
					nMotorEncoder[motorC] = 0;
					while(nMotorEncoder[motorC] > -180)
					{
							motor[motorB] = 0;
							motor[motorC] = -50;
					}
					motor[motorB] = 20;
					motor[motorC] = 20;
					wait1Msec(100);
			}
	}
	bFloatDuringInactiveMotorPWM = false;  // If on the black area
	motor[motorB] = 0;
	motor[motorC] = 0;
}
