#pragma config(Sensor, S1,     sonar,          sensorSONAR)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int ssv, tsv, lsv;
	int x = 3, y = 2;
	int direction =0;//set variables
	int j=0;
	while(lsv > -20) // not on the black area.
	{
		ssv = SensorValue[sonar];      //set variables
		tsv = SensorValue[touch];
		lsv = SensorValue[light];
	//nxtDisplayTextLine(0, "%d ", direction);
//	nxtDisplayTextLine(1, "%d ", j);

		if((ssv >= 5) && (ssv <= 12))     // when distance to right wall is 10cm <= ssv <= 20cm
		{
			if((direction ==0)&&(j>=8)&&(j<15)){
				direction = 1;
			}
			else if((direction ==1)&&(j>=8)&&(j<15)){
				direction = 2;
			}
			else if((direction ==2)&&(j>=8&&(j<15))){
				direction = 3;
			}
			else if((direction ==3)&&(j>=8)&&(j<15)){
				direction =0;
			}
			else if((direction==0)&&(j>=15)){
				direction=2;
			}else if((direction==1)&&(j>=15)){
				direction=3;
			}else if((direction==2)&&(j>=15)){
				direction=0;
			}else if((direction==3)&&(j>=15)){
				direction=1;
			}
			j=0;

			motor[motorB] = 25;
			motor[motorC] = 25;
			wait1Msec(200);

			if(direction ==0){
				y++;
			}
			else if(direction ==1){
				x++;
			}
			else if(direction ==2){
				y--;
			}
			else if(direction ==3){
				x--;
			}

			nxtSetPixel(x,y);
		}
		if((ssv > 12)&&(ssv <=255)) // when distance to right wall over 20cm then turn right
		{
			motor[motorB] = 20;
			motor[motorC] = 50;
			wait1Msec(100);
			j++;
		}
		if((ssv <5)&&(ssv >= 0)) // when distance to right wall under 10cm then turn left
		{
			motor[motorB] = 30;
			motor[motorC] = 15;
			wait1Msec(50);
		}
		if(tsv == 1) //  if there is touch
		{
			bFloatDuringInactiveMotorPWM = false;
			//wait1Msec(500);
			motor[motorB] = -20;
			motor[motorC] = -20;
			wait1Msec(400);
			//bFloatDuringInactiveMotorPWM = false;
			//wait1Msec(1000);
			motor[motorB] = 10;
			motor[motorC] = -30;//turn left
			wait1Msec(850);
			motor[motorB] = 20;
			motor[motorC] = 20;
			wait1Msec(100);

			if (direction ==0){
				direction =3;
			}
			else if (direction ==1){
				direction =0;
			}
			else if (direction ==2){
				direction =1;
			}
			else if (direction ==3){
				direction =2;
			}
		}

		bFloatDuringInactiveMotorPWM = false;  // If on the black area
		motor[motorB] = 0;
		motor[motorC] = 0;
	}
}
